优化README
wechatpay-apiv3/wechatpay-php pull request #65
Opened 2021-11-26 12:13 UTC by xy-peng

docs: 调整了内容组织，使用了更直接和简洁的语言

2021-11-26 12:44 UTC, TheNorthMemory approved these changes
LGTM

2021-11-26 13:22 UTC, TheNorthMemory commented on README_APIv2.md
> +->v2->mmpaysptrans->pay_bank
这个地方，`chain`拼写错了，帮修正一下吧，正确的是： `->v2->mmpaymkttransfers->pay_bank

2021-11-27 09:43 UTC, tpirc3 approved these changes

2021-11-27 13:35 UTC, TheNorthMemory commented on README.md
> +GET /v3/pay/transactions/out-trade-no/{{out_trade_no}
`{{out_trade_no}` 多了个左花括号

2021-11-27 13:35 UTC, TheNorthMemory commented on README.md
> ++ Path 变量使用 `{'{variable_name}'}` 方式书写。例如 `v3->pay->transaction->id->{'{transaction_id}'}`
`Path` 中的 `url_template` 支持两种写法，在IDE提示里是按照 `_variable_name_` 这种方式链接，字面量 `{'{variable_name}'} 写法目前主流IDE还不能自动识别，顾这里推荐以 `_variable_name_` 方式填写。

2021-11-29 02:26 UTC, xy-peng commented on README.md
> ++ Path 变量使用 `{'{variable_name}'}` 方式书写。例如 `v3->pay->transaction->id->{'{transaction_id}'}`
那示例也要跟着改一下？

2021-11-29 03:30 UTC, EmmetZC requested changes

2021-11-29 03:30 UTC, EmmetZC commented on README.md
> +            'contact_name'      => $encryptor('value of `contact_name`'),
placeholder 的表达方法不太统一，这里用：
`$encryptor('{your_contact_name}')` 
或者是
`$encryptor('example_contact_code')` 
会不会更清楚？

2021-11-29 05:05 UTC, xy-peng commented on README.md
> +            'contact_name'      => $encryptor('value of `contact_name`'),
参考其他地方，改用了虚假的“真实”示例值

2021-11-29 06:28 UTC, EmmetZC approved these changes

2021-11-29 07:16 UTC, merged